const fs = require('fs');
const path = require('path');

// Get environment variables from Vercel/system
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const geminiApiKey = process.env.GEMINI_API_KEY || '';

// Check if required variables are present
if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️ Warning: Supabase credentials not found in environment variables');
}

// Generate the environment file content
const environmentContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: true,
  supabase: {
    url: '${supabaseUrl}',
    anonKey: '${supabaseAnonKey}',
  },
  geminiApiKey: '${geminiApiKey}',
  
  ai: {
    ocrEndpoint: '${supabaseUrl}/functions/v1/ocr',
    classificationEndpoint: '${supabaseUrl}/functions/v1/classify-items',
    mealRecommendationEndpoint: '${supabaseUrl}/functions/v1/meal-recommendation'
  }
};
`;

// Write to environment.prod.ts
const targetPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(targetPath, environmentContent);

console.log('✅ Environment file generated successfully at:', targetPath);
console.log('📝 Supabase URL:', supabaseUrl ? '***configured***' : '❌ MISSING');
console.log('📝 Supabase Key:', supabaseAnonKey ? '***configured***' : '❌ MISSING');
console.log('📝 Gemini API Key:', geminiApiKey ? '***configured***' : '❌ MISSING');